# Template
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="typewritten/typewritten"
TYPEWRITTEN_PROMPT_LAYOUT="pure"
TYPEWRITTEN_SYMBOL="$"
TYPEWRITTEN_COLOR_MAPPINGS="primary:blue"
TYPEWRITTEN_COLORS="arrow:yellow;symbol:yellow"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias vim='nvim'

export EDITOR='vim'

export PATH=$HOME/.emacs.d/bin:$PATH
